### ISSUE TITLE
Radial caps don't specify height

### ISSUE THREAD

**Issue by SchrodingersGat** [KiCad/Capacitors_THT.pretty#14]
radial capacitors do not specify component height in the filename.
@jkriege2 I believe you scripted these ones? Can you please update the script to include `L` parameter such as for the axial varieties?

**Comment by SchrodingersGat** [comment]
Also, while you are re-scripting please change 3D model scaling to 1:1:1 (there are new 3D models incoming thanks to @easyw )

**Comment by easyw** [comment]
I have only Radial THT models ...

**Comment by SchrodingersGat** [comment]
@easyw I got them mixed up, I have updated the comment

**Comment by jkriege2** [comment]
Hi!

hmmm ... I thought about coding the height, but the problem is: that will multiply the footprints in the lib! Typically there are several height variants for each footprint-size variant, so which ones should I take and how many caps do we want? When making the footpritns and models, I decided it should be enough to specify the footprint, so you can put any cap that you want, as long as its diameter and pin-distance (...) match. For the 3D models I then chose reasonable heights.

the models are made with KiCAD, by having a "master"-model that is parametrized via a spreadsheet. Then my footprint-scripts generate a python script that is simply run within Freecad and then sets (one-after-the-other) the correct parameters and exports all the 3D models automatically.

1. So: Which caps will be updated ... and with which parameters? ALso I think I already put a lot of work into the models (and could create STP-files for these too) ... why new ones?
2. Do we really want all height variants (e.g. there are 10x12, 10x15, 10x19.5, 10x25, 10x30, 10x40, 10x45, 10x50 ... and that's just from 1 company ... http://www.yageo.com/exep/pages/download/literatures/E-cap_2011.pdf
3. It gets even worse for e.g. MKH-caps (not elkos, but the same problem): http://cdn-reichelt.de/documents/datenblatt/B300/MKH100_MKH250_MKH400%23SIE.pdf

Best,
JAN

**Comment by SchrodingersGat** [comment]
I would tend to agree that we should let user decide on which 3D model to associate. @easyw are you OK with this?

**Comment by easyw** [comment]
Hi @jkriege2 Jan, I noticed that Capacitor THT models were already done in MCAD way after reworking an old 3d model I have in my script tools... (I don't use very often THT components) ... I opened your FC models and they look very well IMO, so I would suggest to keep them for the library. I still would prefer to add height in library kicad_mod and 3d model because is a parameter important for mechanical production... I agree that in the library just few variant can be managed, and the user can easily modify the FC model to fit its needs. Anyway I leave these decision up to you as librarian... thanks for your valuable work! :)
About STEP what I would suggest then is:
- assign color (just diffuse color is fine) to your model parts as in the Materials doc from Mario Luzeiro
- make a union of all the object with the name of your 3d model
- generate STEP models from your parametric models exporting the fused object with FC 0.15 to avoid extra ASSEMBLY structure and check if the exported model is correctly fused as a single object re-importing it
- export from inside FC with a script the WRL models scaled 1/2.54 and assigning Materials corresponding to the ones of the doc (so the kicad_mod will have scale to (1,1,1))
These tips come from the experience I made in my MCAD library and with FC as you can find at the kicad and freecad forum...
Here attached an example of the STEP and WRL files I obtained from your model 
[CP_Radial_D10.0mm_P3.50mm-STP-WRL-example.zip](https://github.com/KiCad/Capacitors_THT.pretty/files/812972/CP_Radial_D10.0mm_P3.50mm-STP-WRL-example.zip)
I already have scripts with the exporting part to obtain WRL optimized in size and Material properties, so you could get some tips there ...
Thx and BR
Maurice

**Comment by evanshultz** [comment]
Gentlemen, as part of going through the libraries and trying to close or resolve issues, is there an update on this item?

I would prefer not to flood the library with a load of new footprints differentiated by height, but certainly we do want to make all 3D models available for selection by the user. I don't know the solution, but I like that all sides are being considered above. :)

**Comment by SchrodingersGat** [comment]
I'm happy to close this, I think that the library footprints should not be unnecessarily duplicated.
